name: A_reg
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  PASSWORD: ${{ secrets.PASSWORD }}
  ABC: ${{ secrets.DC_TOKEN }}

jobs:
  reg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod 777 MinecraftClient-20231120-234-linux-x64
          chmod 777 reg.sh
          sed -i 's/{{PASSWORD}}/'"$PASSWORD"'/g' reg.ini
          echo $PASSWORD
          echo $ABC
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
