name: isyyo
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run shell script
      run: bash run.sh