name: hiwer
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  PASSWOLD: ${{ secrets.PASSWOLD }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化
      uses: actions/checkout@v2

    - name: 赋予权限
      run: chmod 777 MinecraftClient-20230623-225-linux-x64

    - name: 启动
      run: ./MinecraftClient-20230623-225-linux-x64 hiwer.ini