name: reg
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod 777 MinecraftClient-20230623-225-linux-x64
      - name: Setup Debug Session
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: sed -i 's/{{PASSWD}}/'"$PASSWD"'/g' reg.sh
        uses: csexton/debugger-action@master