name: reg
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  reg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod 777 MinecraftClient-20230623-225-linux-x64
          chmod 777 reg.sh
          sed -i 's/{{PASSWORD}}/'"$PASSWORD"'/g' reg.sh
      - name: Setup Debug Session
        uses: csexton/debugger-action@master