name: urine
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  PASSWORD: ${{ secrets.PASSWORD }}
  DC_TOKEN: ${{ secrets.DC_TOKEN }}

jobs:
  urine:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化
      uses: actions/checkout@v2

    - name: 赋予权限
      run: chmod 777 MinecraftClient-20230623-225-linux-x64

    - name: 启动
      run: |
        sed -i 's/{{PASSWORD}}/'"$PASSWORD"'/g' urine.ini
        sed -i 's/{{DC_TOKEN}}/'"$DC_TOKEN"'/g' urine.ini
        ./MinecraftClient-20230623-225-linux-x64 urine.ini