name: V
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  USERNAME: ${{ secrets.V_USERNAME }} # 玩家ID
  ChannelId: '1180503067997769748' # DC频道ID
  PASSWORD: ${{ secrets.PASSWORD }}
  DC_TOKEN: ${{ secrets.DC_TOKEN }}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化
      uses: actions/checkout@v2

    - name: 赋予权限
      run: |
        chmod 777 MinecraftClient-20231120-234-linux-x64
        chmod 777 login.sh

    - name: 启动
      run: |
        sed -i 's/{{USERNAME}}/'"$USERNAME"'/g' V_mcc.ini
        sed -i 's/{{PASSWORD}}/'"$PASSWORD"'/g' V_mcc.ini
        sed -i 's/{{DC_TOKEN}}/'"$DC_TOKEN"'/g' V_mcc.ini
        sed -i 's/{{ChannelId}}/'"$ChannelId"'/g' V_mcc.ini
        ./login.sh
