name: zhtmak
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

env:
  USERNAME: zhtmak # 玩家ID
  PASSWORD: ${{ secrets.PASSWORD }}
  DC_TOKEN: ${{ secrets.DC_TOKEN }}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化
      uses: actions/checkout@v2

    - name: 赋予权限
      run: |
        chmod 777 MinecraftClient-20231120-234-linux-x64
        echo 登录: $USERNAME

    - name: 启动
      run: |
        sed -i 's/{{USERNAME}}/'"$USERNAME"'/g' mcc.ini
        sed -i 's/{{PASSWORD}}/'"$PASSWORD"'/g' mcc.ini
        sed -i 's/{{DC_TOKEN}}/'"$DC_TOKEN"'/g' mcc.ini
        ./MinecraftClient-20231120-234-linux-x64 mcc.ini
